.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH GIAC 1 "July 26, 2002"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
giac \- computer algebra system
.SH SYNOPSIS
.B giac
.RI [ options ] " files" ...
.br
.B cas
.RI [ options ] " files" ...
.br
.B xcas
.RI [ options ] " files" ...
.SH DESCRIPTION
This manual page documents briefly the
.B giac
and
.B cas
commands. The
.B xcas
version shows a nice GUI for the program.
This manual page was written for the Debian distribution
because the original program does not have a manual page.
Instead, it has documentation in the GNU Info format; see below.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics, 
.\" respectively.
\fBgiac\fP is an advance symbolic and numeric calculator by
Bernard Parisse. 
.SH OPTIONS
These programs follow the usual GNU command line syntax, with long
options starting with two dashes (`-').
A summary of options is included below.
For a complete description, see the Info files.
.TP
.B \-h, \-\-help
Show summary of options.
.TP
.B \-v, \-\-version
Show version of program.
.SH SEE ALSO
The programs are documented fully by
.IR "GIAC/XCAS manual" ,
available via the Info system.
.br
Docs in DVI format in /usr/share/doc/giac directory.
.SH AUTHOR
This manual page was written by Carleos Artime <carleos@pinon.ccu.uniovi.es>,
for the Debian GNU/Linux system (but may be used by others).
