#ifndef MEMORY_MAP_H
#define MEMORY_MAP_H

#define RAM_START_VIRT_ADDR			0xC0000000

#define TOTAL_PHY_MEMORY			0x00080000

#define END_OF_KHEAP_PHY_ADDR		TOTAL_PHY_MEMORY		//0x80000

#define PAGE_SIZE					4096
	
#define KHEAP_MAP_PHY_START			0x3F000
	
#define KHEAP_MEMORY_VIR_START		0xD0000000		// 1 MB
	
#define PHY_KHEAP_MEMORY_PAGES		((END_OF_KHEAP_PHY_ADDR - KHEAP_MAP_PHY_START) / PAGE_SIZE)
	
#define BUFFER_PAGES				4
	
#define PAGES_PER_MIB				256
	
	
#define VM_SECTION_NUM				6
	
#define PAGE_TABLE_SIZE				0x400		//1KB

#define TINY_PAGE_SIZE				1024		//1KB





#endif