#! /bin/bash
gcc-4.2 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -m64  -pipe -I/Applications/usr/include -I/System/Library/Frameworks/Python.framework/Versions/2.6/include/python2.6 -c giacpy.cpp -o build/temp.macosx-10.6-universal-2.6/giacpy.o -D HAVE_CONFIG
g++-4.2 -Wl,-F. -bundle -undefined dynamic_lookup -m64  build/temp.macosx-10.6-universal-2.6/giacpy.o -L/Applications/usr/lib -lgiac -o giacpy.so
cp giacpy.so /Applications/usr/lib/python2.6/site-packages
gcc-4.2 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -m64  -pipe -I/Applications/usr/include -I/usr/64/include/python2.7 -c giacpy.cpp -o build/giacpy.o -D HAVE_CONFIG
g++-4.2 -Wl,-F. -bundle -undefined dynamic_lookup -m64  build/giacpy.o -L/Applications/usr/lib -lgiac -o giacpy.so
cp giacpy.so /Applications/usr/lib/python2.7/site-packages