#! /bin/bash
if [  "`which texmacs`" == "" ]; 
then 
   echo "texmacs not found"
else
    if [ -f "$1" ]
    then
	texmacs $1 $2 $3 $4 $5 $6 $7 $8 $9 &
    else
	texmacs -x '(make-session "giac" "default")' &
    fi
fi

