//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by EMU48.RC
//
#define IDI_EMU48                       100
#define IDR_MENU                        101
#define IDR_DEBUG                       102
#define IDR_DEBUG_CODE                  103
#define IDR_DEBUG_MEM                   104
#define IDD_ABOUT                       105
#define IDD_SETTINGS                    106
#define IDD_CHOOSEKML                   107
#define IDD_KMLLOG                      108
#define IDD_DISASM                      109
#define IDD_DEBUG                       110
#define IDD_NEWVALUE                    111
#define IDD_ENTERADR                    112
#define IDD_BREAKEDIT                   113
#define IDD_ENTERBREAK                  114
#define IDD_INSTRUCTIONS                115
#define IDD_FIND                        116
#define IDB_CHECKBOX                    120
#define IDC_PORT1WR                     1000
#define IDC_AUTOSAVE                    1001
#define IDC_AUTOSAVEONEXIT              1002
#define IDC_EMU48DIR                    1003
#define IDC_KMLSCRIPT                   1004
#define IDC_AUTHOR                      1005
#define IDC_TITLE                       1006
#define IDC_KMLLOG                      1007
#define IDC_VERSION                     1008
#define IDC_PORT2ISSHARED               1009
#define IDC_PORT2                       1010
#define IDC_ALWAYSDISPLOG               1011
#define IDC_UPDATE                      1012
#define IDC_LICENSE                     1013
#define IDC_REALSPEED                   1014
#define IDC_PORT1EN                     1015
#define IDC_WIRE                        1016
#define IDC_IR                          1017
#define IDC_DISASM_WIN                  1018
#define IDC_DISASM_MAP                  1019
#define IDC_DISASM_ROM                  1020
#define IDC_DISASM_RAM                  1021
#define IDC_DISASM_PORT1                1022
#define IDC_DISASM_PORT2                1023
#define IDC_DISASM_MODULE               1024
#define IDC_DISASM_HP                   1025
#define IDC_DISASM_CLASS                1026
#define IDC_ADDRESS                     1027
#define IDC_DISASM_ADR                  1028
#define IDC_DISASM_NEXT                 1029
#define IDC_DISASM_COPY                 1030
#define IDC_DEBUG_CODE                  1031
#define IDC_STATIC_CODE                 1032
#define IDC_STATIC_REGISTERS            1033
#define IDC_STATIC_MEMORY               1034
#define IDC_STATIC_STACK                1035
#define IDC_REG_A                       1036
#define IDC_REG_B                       1037
#define IDC_REG_C                       1038
#define IDC_REG_D                       1039
#define IDC_REG_R0                      1040
#define IDC_REG_R1                      1041
#define IDC_REG_R2                      1042
#define IDC_REG_R3                      1043
#define IDC_REG_R4                      1044
#define IDC_REG_D0                      1045
#define IDC_REG_D1                      1046
#define IDC_REG_P                       1047
#define IDC_REG_PC                      1048
#define IDC_REG_OUT                     1049
#define IDC_REG_IN                      1050
#define IDC_REG_ST                      1051
#define IDC_REG_CY                      1052
#define IDC_REG_MODE                    1053
#define IDC_REG_MP                      1054
#define IDC_REG_SR                      1055
#define IDC_REG_SB                      1056
#define IDC_REG_XM                      1057
#define IDC_MISC_INT                    1058
#define IDC_MISC_KEY                    1059
#define IDC_MISC_BS                     1060
#define IDC_NEWVALUE                    1061
#define IDC_ENTERADR                    1062
#define IDC_DEBUG_MEM                   1063
#define IDC_DEBUG_MEM_ADDR              1064
#define IDC_DEBUG_MEM_COL0              1065
#define IDC_DEBUG_MEM_COL1              1066
#define IDC_DEBUG_MEM_COL2              1067
#define IDC_DEBUG_MEM_COL3              1068
#define IDC_DEBUG_MEM_COL4              1069
#define IDC_DEBUG_MEM_COL5              1070
#define IDC_DEBUG_MEM_COL6              1071
#define IDC_DEBUG_MEM_COL7              1072
#define IDC_DEBUG_MEM_TEXT              1073
#define IDC_DEBUG_STACK                 1074
#define IDC_STATIC_BREAKPOINT           1075
#define IDC_BREAKEDIT_ADD               1076
#define IDC_BREAKEDIT_DELETE            1077
#define IDC_BREAKEDIT_WND               1078
#define IDC_STATIC_MMU                  1079
#define IDC_MMU_IO_A                    1080
#define IDC_MMU_NCE2_A                  1081
#define IDC_MMU_CE1_A                   1082
#define IDC_MMU_CE2_A                   1083
#define IDC_MMU_NCE3_A                  1084
#define IDC_MMU_IO_S                    1085
#define IDC_MMU_CE1_S                   1086
#define IDC_MMU_CE2_S                   1087
#define IDC_MMU_NCE2_S                  1088
#define IDC_MMU_NCE3_S                  1089
#define IDC_STATIC_MISC                 1090
#define IDC_MISC_BS_TXT                 1091
#define IDC_INSTR_TEXT                  1092
#define IDC_INSTR_CODE                  1093
#define IDC_INSTR_COPY                  1094
#define IDC_INSTR_CLEAR                 1095
#define IDC_BPCODE                      1096
#define IDC_BPACCESS                    1097
#define IDC_BPREAD                      1098
#define IDC_BPWRITE                     1099
#define IDC_FIND_DATA                   1100
#define IDC_FIND_ASCII                  1101
#define IDC_FIND_CASE                   1102
#define ID_FILE_NEW                     40001
#define ID_FILE_OPEN                    40002
#define ID_FILE_SAVE                    40003
#define ID_FILE_SAVEAS                  40004
#define ID_FILE_EXIT                    40005
#define ID_VIEW_COPY                    40006
#define ID_VIEW_SETTINGS                40007
#define ID_VIEW_RESET                   40008
#define ID_OBJECT_LOAD                  40009
#define ID_OBJECT_SAVE                  40010
#define ID_ABOUT                        40011
#define ID_FILE_CLOSE                   40013
#define ID_BACKUP_SAVE                  40014
#define ID_BACKUP_RESTORE               40015
#define ID_BACKUP_DELETE                40016
#define ID_VIEW_SCRIPT                  40017
#define ID_STACK_COPY                   40019
#define ID_STACK_PASTE                  40020
#define ID_TOOL_DISASM                  40021
#define ID_TOOL_DEBUG                   40022
#define ID_DEBUG_RUN                    40023
#define ID_DEBUG_RUNCURSOR              40024
#define ID_DEBUG_STEP                   40025
#define ID_DEBUG_STEPOVER               40026
#define ID_DEBUG_BREAK                  40027
#define ID_DEBUG_STEPOUT                40028
#define ID_BREAKPOINTS_SETBREAK         40029
#define ID_BREAKPOINTS_CODEEDIT         40030
#define ID_BREAKPOINTS_CLEARALL         40031
#define ID_BREAKPOINTS_NOP3             40032
#define ID_BREAKPOINTS_RPL              40033
#define ID_DEBUG_CODE_GOADR             40034
#define ID_DEBUG_CODE_GOPC              40035
#define ID_DEBUG_CODE_SETPCTOSELECT     40036
#define ID_DEBUG_MEM_GOADR              40037
#define ID_DEBUG_MEM_GOPC               40038
#define ID_DEBUG_MEM_GOD0               40039
#define ID_DEBUG_MEM_GOD1               40040
#define ID_DEBUG_MEM_GOSTACK            40041
#define ID_DEBUG_MEM_FIND               40042
#define ID_INFO_LASTINSTRUCTIONS        40043
#define ID_INTR_STEPOVERINT             40044
#define IDC_SWAP                        40045

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        121
#define _APS_NEXT_COMMAND_VALUE         40046
#define _APS_NEXT_CONTROL_VALUE         1105
#define _APS_NEXT_SYMED_VALUE           108
#endif
#endif
