OUTPUT_ARCH(arm)
ENTRY(_boot)
SECTIONS
{
/*	. = 0x00009200;*/
	
	. = 0x00001000;
	__VRAM_BASE = .;
	
	. = 0x0000A000;
	__DMA_NAND_PALLOAD_BUFFER = .;
	. = . + 0x1000;
	__DMA_NAND_AUXILIARY_BUFFER = .;
	

	. = 0x0000C000;
	.text : { *(.text) }
	.data : { *(.data) }
	
	__bss_start__ = .;
	.bss  : { *(.bss) }
	__bss_end__ = .;
	
	__exidx_start = .;


	__exidx_end = .;

	/*. = 0x32000;*/
	__HEAP_START = .;
}
